apiVersion: v1
kind: Service
metadata:
  name: esnodeport
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: elasticsearch-tcpport30920
    nodePort: 30920
    port: 9200
    protocol: TCP
  type: NodePort
